package com.friendslikethese.backend.config;
import com.fasterxml.jackson.databind.ObjectMapper;import com.friendslikethese.backend.common.ApiError;import jakarta.servlet.http.HttpServletResponse;import org.springframework.beans.factory.annotation.Value;import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.security.authentication.*;import org.springframework.security.config.Customizer;import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.csrf.CookieCsrfTokenRepository;import org.springframework.web.cors.*;import java.time.OffsetDateTime;import java.util.*;
@Configuration public class SecurityConfig{
 private final List<String> origins;private final ObjectMapper json;public SecurityConfig(@Value("${app.cors.allowed-origins:http://localhost:5173}")String origins,ObjectMapper json){this.origins=Arrays.stream(origins.split(",")).map(String::trim).filter(s->!s.isBlank()).toList();this.json=json;}
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder(12);}@Bean AuthenticationManager authenticationManager(AuthenticationConfiguration c)throws Exception{return c.getAuthenticationManager();}
 @Bean SecurityFilterChain securityFilterChain(HttpSecurity http)throws Exception{CookieCsrfTokenRepository csrf=CookieCsrfTokenRepository.withHttpOnlyFalse();csrf.setCookiePath("/");http.cors(Customizer.withDefaults()).csrf(c->c.csrfTokenRepository(csrf)).authorizeHttpRequests(a->a.requestMatchers(HttpMethod.OPTIONS,"/**").permitAll().requestMatchers(HttpMethod.GET,"/api/auth/csrf","/api/auth/me","/api/events/current","/api/teams/leaderboard","/api/events/current/rounds","/api/events/current/rounds/*/leaderboard","/api/public/registration").permitAll().requestMatchers(HttpMethod.POST,"/api/auth/login").permitAll().requestMatchers("/api/**").hasRole("ADMIN").anyRequest().permitAll()).exceptionHandling(e->e.authenticationEntryPoint((req,res,ex)->write(res,401,"Authentication required.")).accessDeniedHandler((req,res,ex)->write(res,403,"Access denied."))).requestCache(c->c.disable()).formLogin(c->c.disable()).httpBasic(c->c.disable()).logout(c->c.disable());return http.build();}
 private void write(HttpServletResponse response,int status,String message)throws java.io.IOException{response.setStatus(status);response.setContentType(MediaType.APPLICATION_JSON_VALUE);json.writeValue(response.getOutputStream(),new ApiError(OffsetDateTime.now(),status,HttpStatus.valueOf(status).getReasonPhrase(),message));}
 @Bean CorsConfigurationSource corsConfigurationSource(){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(origins);c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Content-Type","X-XSRF-TOKEN"));c.setAllowCredentials(true);UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
