package com.friendslikethese.backend.auth;
import jakarta.servlet.http.*;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.authentication.*;import org.springframework.security.core.*;import org.springframework.security.core.context.*;import org.springframework.security.web.context.*;import org.springframework.web.bind.annotation.*;import org.springframework.security.web.csrf.CsrfToken;
@RestController @RequestMapping("/api/auth") public class AuthController{
 private final AuthenticationManager manager;private final AdminUserRepository users;private final SecurityContextRepository contexts=new HttpSessionSecurityContextRepository();private final LoginThrottle throttle;
 public AuthController(AuthenticationManager manager,AdminUserRepository users,LoginThrottle throttle){this.manager=manager;this.users=users;this.throttle=throttle;}
 @GetMapping("/csrf") public java.util.Map<String,String> csrf(CsrfToken token){return java.util.Map.of("token",token.getToken(),"headerName",token.getHeaderName());}
 @PostMapping("/login") public AuthResponse login(@Valid @RequestBody LoginRequest request,HttpServletRequest http,HttpServletResponse response){String key=http.getRemoteAddr()+":"+request.username().trim().toLowerCase();throttle.check(key);try{Authentication auth=manager.authenticate(new UsernamePasswordAuthenticationToken(request.username(),request.password()));SecurityContext context=SecurityContextHolder.createEmptyContext();context.setAuthentication(auth);SecurityContextHolder.setContext(context);contexts.saveContext(context,http,response);AdminUser user=users.findByUsernameIgnoreCaseAndEnabledTrue(auth.getName()).orElseThrow();user.recordLogin();users.save(user);throttle.succeeded(key);return view(user);}catch(AuthenticationException ex){throttle.failed(key);throw new BadCredentialsException("Invalid username or password.");}}
 @GetMapping("/me") public AuthResponse me(Authentication authentication){if(authentication==null||!authentication.isAuthenticated()||authentication instanceof AnonymousAuthenticationToken)return new AuthResponse(false,null,null,null,null);return view(users.findByUsernameIgnoreCaseAndEnabledTrue(authentication.getName()).orElseThrow());}
 @PostMapping("/logout") public ResponseEntity<Void> logout(HttpServletRequest request){try{request.logout();}catch(Exception ignored){}HttpSession session=request.getSession(false);if(session!=null)session.invalidate();SecurityContextHolder.clearContext();return ResponseEntity.noContent().build();}
 private AuthResponse view(AdminUser user){return new AuthResponse(true,user.getUsername(),user.getEmail(),user.getDisplayName(),user.getRole());}
}
