package com.friendslikethese.backend.auth;
import com.friendslikethese.backend.event.*;
import com.friendslikethese.backend.team.*;
import com.friendslikethese.backend.registration.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.mock.web.MockHttpSession;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.*;import org.springframework.transaction.annotation.Transactional;import java.util.List;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Transactional class SecurityIntegrationTest{
 @Autowired MockMvc mvc;@Autowired AdminUserRepository users;@Autowired PasswordEncoder encoder;@MockitoBean GoogleSheetsClient sheets;@Autowired EventService eventService;@Autowired EventRepository events;@Autowired TeamRepository teams;
 @BeforeEach void admin(){users.save(new AdminUser("securityadmin","admin-security@example.test",encoder.encode("valid-password"),"Security Admin"));}
 @Test void publicScoreboardApisAreAnonymousAndDoNotLeakMembers()throws Exception{mvc.perform(get("/api/events/current")).andExpect(status().isOk());mvc.perform(get("/api/teams/leaderboard")).andExpect(status().isOk()).andExpect(jsonPath("$[0].members").doesNotExist());mvc.perform(get("/api/events/current/rounds")).andExpect(status().isOk());mvc.perform(get("/api/public/registration")).andExpect(status().isOk()).andExpect(jsonPath("$.registrationFormUrl").exists());}
 @Test void administrativeApisRejectAnonymousRequests()throws Exception{mvc.perform(get("/api/teams")).andExpect(status().isUnauthorized());mvc.perform(post("/api/teams/00000000-0000-0000-0000-000000000001/score").with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amount\":5,\"reason\":\"test\"}")).andExpect(status().isUnauthorized());mvc.perform(post("/api/events/current/rounds/1/start").with(csrf())).andExpect(status().isUnauthorized());mvc.perform(post("/api/registrations/import").with(csrf())).andExpect(status().isUnauthorized());mvc.perform(post("/api/teams/scores/reset").with(csrf())).andExpect(status().isUnauthorized());}
 @Test void csrfRejectsStateChangeBeforeAuthorization()throws Exception{mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"securityadmin\",\"password\":\"valid-password\"}")).andExpect(status().isForbidden());}
 @Test void loginMeAndLogoutUseServerSession()throws Exception{MvcResult login=mvc.perform(post("/api/auth/login").with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"securityadmin\",\"password\":\"valid-password\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.authenticated").value(true)).andExpect(jsonPath("$.username").value("securityadmin")).andExpect(jsonPath("$.passwordHash").doesNotExist()).andReturn();MockHttpSession session=(MockHttpSession)login.getRequest().getSession(false);mvc.perform(get("/api/auth/me").session(session)).andExpect(status().isOk()).andExpect(jsonPath("$.username").value("securityadmin")).andExpect(jsonPath("$.email").value("admin-security@example.test"));mvc.perform(get("/api/teams").session(session)).andExpect(status().isOk());mvc.perform(post("/api/auth/logout").session(session).with(csrf())).andExpect(status().isNoContent());mvc.perform(get("/api/teams").session(session)).andExpect(status().isUnauthorized());}
 @Test void invalidAndUnknownCredentialsUseSameResponse()throws Exception{for(String body:List.of("{\"username\":\"securityadmin\",\"password\":\"wrong\"}","{\"username\":\"unknown-admin\",\"password\":\"wrong\"}"))mvc.perform(post("/api/auth/login").with(csrf()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.message").value("Invalid username or password."));}
 @Test void passwordIsBcryptAndAuthenticatedAdminCanImport()throws Exception{AdminUser admin=users.findByUsernameIgnoreCaseAndEnabledTrue("securityadmin").orElseThrow();assertNotEquals("valid-password",admin.getPasswordHash());assertTrue(encoder.matches("valid-password",admin.getPasswordHash()));when(sheets.fetchRegistrations()).thenReturn(new RegistrationBatch(0,0,List.of()));mvc.perform(post("/api/registrations/import").with(user("securityadmin").roles("ADMIN")).with(csrf())).andExpect(status().isOk());}
 @Test void authenticatedAdminCanControlRoundAndScore()throws Exception{Event event=events.findByCurrentTrue().orElseThrow();Team team=teams.save(new Team(event,"Security Scorers"));eventService.closeRegistration();eventService.startGame();mvc.perform(post("/api/events/current/rounds/1/start").with(user("securityadmin").roles("ADMIN")).with(csrf())).andExpect(status().isOk());mvc.perform(post("/api/teams/"+team.getId()+"/score").with(user("securityadmin").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amount\":5,\"reason\":\"security verification\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.score").value(5));}
 @Test void repositoryLooksUpEnabledAdminByUsernameIgnoringCase(){assertTrue(users.findByUsernameIgnoreCaseAndEnabledTrue("SECURITYADMIN").isPresent());}
 @Test void disabledAdministratorIsRejected()throws Exception{AdminUser disabled=users.save(new AdminUser("disabledadmin","disabled@example.test",encoder.encode("valid-password"),"Disabled Admin"));disabled.disable();users.saveAndFlush(disabled);mvc.perform(post("/api/auth/login").with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"disabledadmin\",\"password\":\"valid-password\"}")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.message").value("Invalid username or password."));}
}
